# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.5
language: swift
# podfile: Example/Podfile
before_install:
# - gem install cocoapods # Since Travis is not always on latest version
- gem install bundler
- bundle install
- bundle exec pod install --repo-update --project-directory=Example
cache: cocoapods
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/UIScrollView-InfiniteScrollSwift.xcworkspace -scheme UIScrollView-InfiniteScrollSwift-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
